# AWS Production Profile - apenas configurações específicas de produção
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 3000

logging:
  level:
    com.stefanini.ceptracker: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

app:
  cep-service:
    external-api:
      base-url: https://viacep.com.br
      timeout: 5000
    cache:
      ttl: 3600